In [1]:
import numpy as np
import gym
import gym_custom_envs
import time
import scipy.linalg as alg
env = gym.make("CartPoleContinuous-v0")

In [2]:
mc = env.masscart
mp = env.masspole
l = env.length
g = -env.gravity

In [3]:
M = np.matrix([
    [mc+mp, mp*l],
    [mp*l, mp*(l**2)]
])

print("M = ")
print(M, '\n')

iM = np.linalg.inv(M)

print("iM = ")
print(iM, '\n')
# C(q, q_dot) will be zero as q_dot is zero

dtau_g = np.matrix([
    [0, 0],
    [0, mp*g*l]
])

print("dtau_g = ")
print(dtau_g, '\n')


b = np.matrix([
    [1., 0],
    [0., 0]
])

print("b")
print(b, '\n')

M = 
[[1.1   0.05 ]
 [0.05  0.025]] 

iM = 
[[ 1. -2.]
 [-2. 44.]] 

dtau_g = 
[[ 0.    0.  ]
 [ 0.   -0.49]] 

b
[[1. 0.]
 [0. 0.]] 



In [4]:
def lqr(A, B, Q, R):

    S = np.matrix(alg.solve_continuous_are(A, B, Q, R))
    
    K = np.matrix(alg.inv(R)*B.T*S)
        
    return K, S

In [5]:
A = np.concatenate((
    np.concatenate((np.zeros((2,2)), np.eye(2)), axis=1),
    np.concatenate((np.dot(iM, dtau_g), np.zeros((2,2))), axis=1)
), axis=0)
    
print("A = ")    
print(A, '\n')   

B = np.concatenate((
    np.zeros((2,2)),
    np.dot(iM, b)
), axis=0)
    
print("B = ")    
print(B, '\n')   

Q = np.matrix([
    [10., 0, 0, 0],
    [0, 10., 0, 0],
    [0, 0, 1., 0],
    [0, 0, 0, 1.]
])
print("Q = ")    
print(Q, '\n')   

R = np.eye(2)
print("R = ")    
print(R, '\n')   



A = 
[[  0.     0.     1.     0.  ]
 [  0.     0.     0.     1.  ]
 [  0.     0.98   0.     0.  ]
 [  0.   -21.56   0.     0.  ]] 

B = 
[[ 0.  0.]
 [ 0.  0.]
 [ 1.  0.]
 [-2.  0.]] 

Q = 
[[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]] 

R = 
[[1. 0.]
 [0. 1.]] 



In [6]:
K, S = lqr(A, B, Q, R)

print("K = ")
print(K, '\n')
print("S = ")
print(S, '\n')

K = 
[[ 3.16227766 -3.06227964  3.15171258 -0.85178011]
 [ 0.          0.          0.          0.        ]] 

S = 
[[ 9.96659028 -2.6935652   4.46664609  0.65218422]
 [-2.6935652  16.81384764 -3.33675029 -0.13723532]
 [ 4.46664609 -3.33675029  4.17686956  0.51257849]
 [ 0.65218422 -0.13723532  0.51257849  0.6821793 ]] 



In [ ]:
from IPython.display import clear_output

for i in range(100):
    s = env.reset().reshape(1, 4)
    done = False
    t = 0
    while not done:
        a = -np.dot(K, s.T)[0, 0]
        ns, r, done, _ = env.step(a)
        env.render()
        s = ns.reshape(1, 4)
        print(t)
        t+=r
        clear_output(wait=True)
#         time.sleep(0.005)
env.close()        

0
